<?php
/** @var \SwedbankPay\Checkout\Block\Adminhtml\Order\View\PaymentInfo $this */
?>

<br />
<p>
    <?php if ($this->getCurrentPaymentId()): ?>
        <strong>SwedbankPay Payment Order ID:</strong> <?php echo $this->getCurrentPaymentId(); ?><br />
    <?php endif; ?>

    <?php if ($this->getCurrentPaymentInstrument()): ?>
        <strong>SwedbankPay Payment Instrument:</strong> <?php echo $this->getCurrentPaymentInstrument(); ?>
    <?php endif; ?>
</p>